var Tasks = function() {

this.getTask = (taskNumber) => {
    return tasks[taskNumber].trim();
};

this.getDisplayedTask = (taskNumber) => {
    return tasks[taskNumber].replace(/\s{2,}/g,' ').trim(); //Regex to remove all whitescape except one between words
};

var tasks = ['Clear',                                                                   //task id 0
'Pick the kids from swimming lessons',                                                  //task id 1
'Get milk',                                                                             //task id 2
'Wash myself',                                                                          //task id 3    
'Sell drugs',                                                                           //task id 4
'☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼ !”#$%&’()*+,-./012',                                   //task id 5
'3456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abbcd',                                  //task id 6
'efghijklmnopqrstuvwxyz{|}~⌂ÇüéâäàåçêëèïîìÄÅÉæÆôöòû',                                   //task id 7
'ùÿÖÜ¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚',                                   //task id 8
'╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·',                                   //task id 9
'√ⁿ²■',                                                                                 //task id 10
'0',                                                                                    //task id 11
'1',                                                                                    //task id 12
'a',                                                                                    //task id 13
'B',                                                                                    //task id 14
'!Casket',                                                                              //task id 15
'"suppe',                                                                               //task id 16
'wer123',                                                                               //task id 17
'098op098op098op098op098op098op098op098op098op098op098op098op098op098op098op09op098op', //task id 18
'Part: 546gbfcve',                                                                      //task id 19
'-12',                                                                                  //task id 20
'-asdWENCV',                                                                            //task id 21
'-OZXY,',                                                                               //task id 22
'=321as',                                                                               //task id 23
'Cats',                                                                                 //task id 24
'    ',                                                                                 //task id 25
'  dog   food',                                                                         //task id 26
'my  SOCKS   ',                                                                         //task id 27
'WhItE     wHaLe',                                                                      //task id 28
'cats',                                                                                 //task id 29
'Dogs',                                                                                 //task id 30
'1234',                                                                                 //task id 31
'wrertrwrterrydsvadvasdaysdywggvsvaudsaudysyuaduwudvdc c c',                            //task id 32
'-765',                                                                                 //task id 33
'This IS a random tEXt',                                                                //task id 34
'Cactussssssssssssssss',                                                                //task id 35
'1234555',                                                                              //task id 36
'000000000000000000001',                                                                //task id 37
'Water is too cold',                                                                    //task id 38
'WREWTIREGOFIFSOGIFGORITOETIROETIORETI',                                                //task id 39
'dsnadjaskfjafjsahfjafjasfka][][][][]0))())21241430?"""">}}">',                         //task id 40
'now',                                                                                  //task id 41
'then',                                                                                 //task id 42
'milk',                                                                                 //task id 43
'get some vodka',                                                                       //task id 44
'put the dog to sleep',                                                                 //task id 45
'Cactussssssssssssssss',                                                                //task id 46
'Cactussssssssssssssss',                                                                //task id 47
'Cactussssssssssssssss',                                                                //task id 48
'Cactussssssssssssssss',                                                                //task id 49
'Cactussssssssssssssss',                                                                //task id 50
'Cactussssssssssssssss',                                                                //task id 51
'Cactussssssssssssssss',                                                                //task id 52
'Cactussssssssssssssss',                                                                //task id 53
'Cactussssssssssssssss',                                                                //task id 54
'Cactussssssssssssssss',                                                                //task id 55
'Cactussssssssssssssss',                                                                //task id 56
'Cactussssssssssssssss',                                                                //task id 57
'Cactussssssssssssssss',                                                                //task id 58
'Cactussssssssssssssss',                                                                //task id 59
'Cactussssssssssssssss',                                                                //task id 60
'Cactussssssssssssssss',                                                                //task id 61
'Cactussssssssssssssss',                                                                //task id 62
'Cactussssssssssssssss',                                                                //task id 63
'Cactussssssssssssssss',                                                                //task id 64
'Cactussssssssssssssss',                                                                //task id 65
'Cactussssssssssssssss',                                                                //task id 66
'Cactussssssssssssssss',                                                                //task id 67
'Cactussssssssssssssss',                                                                //task id 68
'Cactussssssssssssssss',                                                                //task id 69
'Cactussssssssssssssss',                                                                //task id 70
'Cactussssssssssssssss',                                                                //task id 71
'Cactussssssssssssssss',                                                                //task id 72
'Cactussssssssssssssss',                                                                //task id 73
'Cactussssssssssssssss',                                                                //task id 74
'Cactussssssssssssssss',                                                                //task id 75
'Cactussssssssssssssss',                                                                //task id 76
'Cactussssssssssssssss',                                                                //task id 77
'Cactussssssssssssssss',                                                                //task id 78
'Cactussssssssssssssss',                                                                //task id 79
'Cactussssssssssssssss',                                                                //task id 80
'Cactussssssssssssssss',                                                                //task id 81
'Cactussssssssssssssss',                                                                //task id 82
'Cactussssssssssssssss',                                                                //task id 83
'Cactussssssssssssssss',                                                                //task id 84
'Cactussssssssssssssss',                                                                //task id 85
'Cactussssssssssssssss',                                                                //task id 86
'Cactussssssssssssssss',                                                                //task id 87
'Cactussssssssssssssss',                                                                //task id 88
'Cactussssssssssssssss',                                                                //task id 89
'Cactussssssssssssssss',                                                                //task id 90
'Cactussssssssssssssss',                                                                //task id 91
'Cactussssssssssssssss',                                                                //task id 92
'Cactussssssssssssssss',                                                                //task id 93
'Cactussssssssssssssss',                                                                //task id 94
'Cactussssssssssssssss',                                                                //task id 95
'1',                                                                                    //task id 96
'a',                                                                                    //task id 97
'1',                                                                                    //task id 98
'a',                                                                                    //task id 99
'1',                                                                                    //task id 100
'a',                                                                                    //task id 101
'1',                                                                                    //task id 102
'a',                                                                                    //task id 103
'1',                                                                                    //task id 104
'a',                                                                                    //task id 105
'1',                                                                                    //task id 106
'a',                                                                                    //task id 107
'1',                                                                                    //task id 108
'a',                                                                                    //task id 109
'1',                                                                                    //task id 110
'a',                                                                                    //task id 111
'1',                                                                                    //task id 112
'a',                                                                                    //task id 113
'1',                                                                                    //task id 114
'a',                                                                                    //task id 115
'1',                                                                                    //task id 116
'a',                                                                                    //task id 117
'1',                                                                                    //task id 118
'a',                                                                                    //task id 119
'1',                                                                                    //task id 120
'a',                                                                                    //task id 121
'1',                                                                                    //task id 122
'a',                                                                                    //task id 123
'1',                                                                                    //task id 124
'a',                                                                                    //task id 125
'1',                                                                                    //task id 126
'a',                                                                                    //task id 127
'1',                                                                                    //task id 128
'a',                                                                                    //task id 129
'1',                                                                                    //task id 130
'a',                                                                                    //task id 131
'1',                                                                                    //task id 132
'a',                                                                                    //task id 133
'1',                                                                                    //task id 134
'a',                                                                                    //task id 135
'1',                                                                                    //task id 136
'a',                                                                                    //task id 137
'1',                                                                                    //task id 138
'a',                                                                                    //task id 139
'1',                                                                                    //task id 140
'a',                                                                                    //task id 141
'1',                                                                                    //task id 142
'a',                                                                                    //task id 143
'1',                                                                                    //task id 144
'a',                                                                                    //task id 145
'1',                                                                                    //task id 146
'a',                                                                                    //task id 147
'1',                                                                                    //task id 148
'a',                                                                                    //task id 149
'1',                                                                                    //task id 150
'a',                                                                                    //task id 151
'1',                                                                                    //task id 152
'a',                                                                                    //task id 153
'1',                                                                                    //task id 154
'a',                                                                                    //task id 155
'1',                                                                                    //task id 156
'a',                                                                                    //task id 157
'1',                                                                                    //task id 158
'a',                                                                                    //task id 159
'1',                                                                                    //task id 160
'a',                                                                                    //task id 161
'1',                                                                                    //task id 162
'a',                                                                                    //task id 163
'1',                                                                                    //task id 164
'a',                                                                                    //task id 165
'1',                                                                                    //task id 166
'a',                                                                                    //task id 167
'1',                                                                                    //task id 168
'a',                                                                                    //task id 169
'1',                                                                                    //task id 170
'a',                                                                                    //task id 171
'1',                                                                                    //task id 172
'a',                                                                                    //task id 173
'1',                                                                                    //task id 174
'a',                                                                                    //task id 175
'1',                                                                                    //task id 176
'a',                                                                                    //task id 177
'1',                                                                                    //task id 178
'a',                                                                                    //task id 179
'1',                                                                                    //task id 180
'a',                                                                                    //task id 181
'1',                                                                                    //task id 182
'a',                                                                                    //task id 183
'1',                                                                                    //task id 184
'a',                                                                                    //task id 185
'1',                                                                                    //task id 186
'a',                                                                                    //task id 187
'1',                                                                                    //task id 188
'a',                                                                                    //task id 189
'1',                                                                                    //task id 190
'a',                                                                                    //task id 191
'1',                                                                                    //task id 192
'a',                                                                                    //task id 193
'1',                                                                                    //task id 194
'a',                                                                                    //task id 195
'1',                                                                                    //task id 196
'a',                                                                                    //task id 197
'1',                                                                                    //task id 198
'a',                                                                                    //task id 199
'1',                                                                                    //task id 200
'a',                                                                                    //task id 201
'1',                                                                                    //task id 202
'a',                                                                                    //task id 203
'1',                                                                                    //task id 204
'a',                                                                                    //task id 205
'1',                                                                                    //task id 206
'a',                                                                                    //task id 207
'1',                                                                                    //task id 208
'a',                                                                                    //task id 209
'1',                                                                                    //task id 210
'a',                                                                                    //task id 211
'1',                                                                                    //task id 212
'a',                                                                                    //task id 213
'1',                                                                                    //task id 214
'a',                                                                                    //task id 215
'1',                                                                                    //task id 216
'a',                                                                                    //task id 217
'1',                                                                                    //task id 218
'a',                                                                                    //task id 219
'1',                                                                                    //task id 220
'a',                                                                                    //task id 221
'1',                                                                                    //task id 222
'a',                                                                                    //task id 223
'1',                                                                                    //task id 224
'a',                                                                                    //task id 225
'1',                                                                                    //task id 226
'a',                                                                                    //task id 227
'1',                                                                                    //task id 228
'a',                                                                                    //task id 229
'1',                                                                                    //task id 230
'a',                                                                                    //task id 231
'1',                                                                                    //task id 232
'a',                                                                                    //task id 233
'1',                                                                                    //task id 234
'a',                                                                                    //task id 235
'1',                                                                                    //task id 236
'a',                                                                                    //task id 237
'1',                                                                                    //task id 238
'a',                                                                                    //task id 239
'-765',                                                                                 //task id 240
'-765',                                                                                 //task id 241
'-765',                                                                                 //task id 242
'-765',                                                                                 //task id 243
'-765',                                                                                 //task id 244
'-765',                                                                                 //task id 245
'-765',                                                                                 //task id 246
'-765',                                                                                 //task id 247
'-765',                                                                                 //task id 248
'-765',                                                                                 //task id 249
'-765',                                                                                 //task id 250
'-765',                                                                                 //task id 251
'-765',                                                                                 //task id 252
'-765',                                                                                 //task id 253
'-765',                                                                                 //task id 254
'-765',                                                                                 //task id 255
'-765',                                                                                 //task id 256
'-765',                                                                                 //task id 257
'-765',                                                                                 //task id 258
'-765',                                                                                 //task id 259
'-765',                                                                                 //task id 260
'-765',                                                                                 //task id 261
'-765',                                                                                 //task id 262
'-765',                                                                                 //task id 263
'-765',                                                                                 //task id 264
'-765',                                                                                 //task id 265
'-765',                                                                                 //task id 266
'-765',                                                                                 //task id 267
'-765',                                                                                 //task id 268
'-765',                                                                                 //task id 269
'-765',                                                                                 //task id 270
'-765',                                                                                 //task id 271
'-765',                                                                                 //task id 272
'-765',                                                                                 //task id 273
'-765',                                                                                 //task id 274
'-765',                                                                                 //task id 275
'-765',                                                                                 //task id 276
'-765',                                                                                 //task id 277
'-765',                                                                                 //task id 278
'-765',                                                                                 //task id 279
'-765',                                                                                 //task id 280
'-765',                                                                                 //task id 281
'-765',                                                                                 //task id 282
'-765',                                                                                 //task id 283
'-765',                                                                                 //task id 284
'-765',                                                                                 //task id 285
'-765',                                                                                 //task id 286
'-765',                                                                                 //task id 287
'-765',                                                                                 //task id 288
'-765',                                                                                 //task id 289
'-765',                                                                                 //task id 290
'-765',                                                                                 //task id 291
'-765',                                                                                 //task id 292
'-765',                                                                                 //task id 293
'-765',                                                                                 //task id 294
'-765',                                                                                 //task id 295
'-765',                                                                                 //task id 296
'-765',                                                                                 //task id 297
'-765',                                                                                 //task id 298
'-765',                                                                                 //task id 299
'-765',                                                                                 //task id 300
'-765',                                                                                 //task id 301
'-765',                                                                                 //task id 302
'-765',                                                                                 //task id 303
'-765',                                                                                 //task id 304
'-765',                                                                                 //task id 305
'-765',                                                                                 //task id 306
'-765',                                                                                 //task id 307
'-765',                                                                                 //task id 308
'-765',                                                                                 //task id 309
'-765',                                                                                 //task id 310
'-765',                                                                                 //task id 311
'-765',                                                                                 //task id 312
'-765',                                                                                 //task id 313
'-765',                                                                                 //task id 314
'-765',                                                                                 //task id 315
'-765',                                                                                 //task id 316
'-765',                                                                                 //task id 317
'-765',                                                                                 //task id 318
'-765',                                                                                 //task id 319
'-765',                                                                                 //task id 320
'-765',                                                                                 //task id 321
'-765',                                                                                 //task id 322
'-765',                                                                                 //task id 323
'-765',                                                                                 //task id 324
'-765',                                                                                 //task id 325
'-765',                                                                                 //task id 326
'-765',                                                                                 //task id 327
'-765',                                                                                 //task id 328
'-765',                                                                                 //task id 329
'-765',                                                                                 //task id 330
'-765',                                                                                 //task id 331
'-765',                                                                                 //task id 332
'-765',                                                                                 //task id 333
'-765',                                                                                 //task id 334
'-765',                                                                                 //task id 335
'-765',                                                                                 //task id 336
'-765',                                                                                 //task id 337
'=321as',                                                                               //task id 338
'=321as',                                                                               //task id 339
'=321as',                                                                               //task id 340
'=321as',                                                                               //task id 341
'=321as',                                                                               //task id 342
'=321as',                                                                               //task id 343
'=321as',                                                                               //task id 344
'=321as'                                                                                //task id 345

];                                                                                         

};
module.exports = new Tasks();
